edition = "2021"
group_imports="StdExternalCrate"
imports_layout="Horizontal"
max_width=120
newline_style="Unix"
reorder_impl_items=true
reorder_imports = true
tab_spaces = 2
trailing_comma="Never"
use_small_heuristics="Default"
